name: streaming_service
description: Streaming service

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  intl: ^0.17.0
  dio: ^4.0.6
  json_annotation: ^4.5.0
  cached_network_image: ^3.2.1
  just_audio: ^0.9.28
  hive: ^2.2.1
  rxdart: ^0.27.4
  flutter_slidable: ^1.3.0
  flutter_html: ^3.0.0-alpha.3
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true